server:
  port: 8081

spring:
  application:
    name: usersFoodCourt

  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # o update / validate / create-drop según necesites
    show-sql: true

  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
      org.springframework.boot.autoconfigure: ERROR

application:
  security:
    jwt:
      secret-key: m2yrnAnikqppG3cqmTOGXExVuVlLxOvaN5q2Gqwel/aigX+wgP68HvbE1ypcpUBv
      expiration: 86400000

appdescription: "API management users"
appversion: "1.0.0"